---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/oxyc/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
dotfiles_files:
  - .agignore
  - .bash_profile
  - .bashrc
  - .dircolors
  - .gitconfig
  - .gitignore
  - .inputrc
  - .lftprc
  - .bash/aliases.sh
  - .bash/colors.sh
  - .bash/exports.sh
  - .bash/functions.sh
  - .bash/prompt.sh
  - .bash/shell.sh
  - .bash/ssh-agent.sh
  - .bash_completion.d/misc
  - .osx/osx.sh

homebrew_installed_packages:
  # Install GNU packages.
  # https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
  - coreutils
  - binutils
  - diffutils
  - { name: ed, install_options: "default-names" }
  - { name: findutils, install_options: "with-default-names" }
  - gawk
  - { name: gnu-indent, install_options: "with-default-names" }
  - { name: gnu-sed, install_options: "with-default-names" }
  - { name: gnu-tar, install_options: "with-default-names" }
  - { name: gnu-which, install_options: "with-default-names" }
  - gnutls
  - { name: grep, install_options: "with-default-names" }
  - gzip
  - screen
  - watch
  - { name: wdiff, install_options: "with-gettext" }
  - wget
  # Update GNU pre-installed packages.
  - bash
  - emacs
  - gdb
  - gpatch
  - less
  - m4
  - make
  - nano
  # Update non-GNU pre-installed packages.
  - file-formula
  - git
  - openssh
  - perl
  - python
  - rsync
  - svn
  - unzip
  - rsync

  # Some other GNU tools.
  - autoconf                  # build tool
  - gettext                   # gnu translation tool
  - gpg                       # gnu privacy guard
  - readline                  # gnu readline

  # More terminal tools.
  - httpie                    # cli http client
  - iperf                     # bandwidth benchmarking
  - lynx                      # browser
  - nmap                      # network mapper
  - openssl                   # ssl/tls toolkit
  - p7zip                     # 7 zip
  - pigz                      # parallel gzip
  - pv                        # pipe viewer
  - wrk                       # http benchmarking
  - zopfli                    # zopfli compression

  # Programming languages
  - lua
  - npm # @todo
  - go
  - php71
  - python3 # required by kitty
  - ruby

  # Libraries
  - luajit                    # required by vim
  - glfw                      # required by kitty.app

  # Essential development tools/libraries.
  - exa                       # ls replacement
  - fasd                      # autojump
  - fzf                       # fuzzy finder
  - khd                       # hotkey daemon
  - massren                   # mass renaming in vim
  - mosh                      # mobile shell
  - rename                    # regex rename
  - ssh-copy-id               # send public key to remote
  - the_silver_searcher       # ag, faster than ack
  - tree                      # recursive directory listing
  - { name: vim, install_options: "with-luajit,without-ruby,override-system-vi" }

  # Shell completions
  - bash-completion2 # bash 4
  - cap-completion
  - open-completion
  - vagrant-completion
  - wpcli-completion

  # Image tools
  - exiv2
  - gifsicle
  - { name: imagemagick, install_options: "with-webp" }
  - mozjpeg
  - optipng
  - pngcheck
  - webp

  # Install font tools.
  - sfnt2woff
  - sfnt2woff-zopfli
  - woff2

homebrew_taps:
  - bramstein/webfonttools
  - caskroom/cask
  - caskroom/fonts
  - homebrew/completions
  - homebrew/core
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions
  - laurent22/massren
  - oxyc/custom

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - font-inconsolata-dz-for-powerline
  - google-chrome
  - lastpass
  - kitty # terminal
  - nvalt
  - slack
  - sublime-text
  - transmission
  - transmit
  - vagrant
  - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

extra_git:
  - repo: https://github.com/chriskempson/base16-shell.git
    dest: ~/.local/lib/base16-shell
  - repo: git@github.com:oxyc/vimrc.git
    dest: ~/Projects/Personal/vimrc

osx_script: ~/.osx/osx.sh
